server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
    metadata-map:
      metrics.path: /actuator/prometheus
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shabbirdwd53/config-server
          clone-on-start: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health", "prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true


eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
    metadata-map:
      metrics.path: /actuator/prometheus
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
   