server:
  port: 9010

spring:
  application:
    name: STOCK-SERVICE
    metadata-map:
      metrics.path: /actuator/prometheus
  zipkin:
    base-url: http://127.0.0.1:9411/

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
    metadata-map:
      metrics.path: /actuator/prometheus
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health", "prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
