apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service-app
  labels:
    app: stock-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-service-app
  template:
    metadata:
      labels:
        app: stock-service-app
    spec:
      containers:
        - name: stock-service-app
          image: akmo03/stock-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9010

---
apiVersion: v1
kind: Service
metadata:
  name: stock-service-lb
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
spec:
  type: LoadBalancer
  ports:
    - targetPort: 9010
      port: 80
  selector:
    app: stock-service-app
