apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
      - name: user-service-app
        image: akmo03/user-service:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-lb
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
spec:
  selector:
    app: user-service-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9002
